services:
  mongo:
    image: mongo:6
    container_name: mongo_container_hotel-app
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hotel-app
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/hotel-app
    # restart: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-booking-nestjs_app
    depends_on:
      test:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    networks:
      - mongo-network
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/hotel-app
    ports:
      - "3001:3000"
    restart: always

volumes:
  mongo_data:

networks:
  mongo-network:
    driver: bridge
